---
title: "purchaseprobability"
author: "D. Danilenko"
date: "2023-05-11"
output: html_document
---

```{r setup, include=FALSE}
# setwd("C:/Users/dand/Documents/GitHub/appliances_interventions")
setwd("/Users/khat/Documents/GitHub/appliances_interventions")
```

```{r}
# load data
load(file="appliances_clean.R")
```

```{r}
# appliances <- read.xlsx("appliances_clean.xlsx")
library(RSQLite)
con <- dbConnect(RSQLite::SQLite(), "/Users/khat/Documents/GitHub/appliances_interventions/appliances_clean.db")
appliances <- dbReadTable(con, "my_table")
dbDisconnect(con)

# load("appliances_clean.R")
```

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(meta)
library(metafor)
library(metadat)
library(haven)
library(writexl)
library(openxlsx)
library(dplyr)
library(stringr)
library(readxl)
library(ggridges)
options(scipen = 999)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_purchase <- data.frame()
# filter to a needed dependent variable
data_purchase <- appliances %>% 
                  filter(dep_variable_purchase_category == "purschase (probability) of efficient appliance")
# exclude the outliers
data_purchase <- data_purchase %>% 
                  filter(z_value > -0.5,
                         z_value < 0.5)
```

```{r}
# include WTP and purchase probability together
data_purchase1 <- data.frame()
# filter to a needed dependent variable
data_purchase1 <- appliances %>%
  filter(dep_variable_purchase_category %in% c("purschase (probability) of efficient appliance", "WTP for efficient appliance"))
# data_purchase1 <- data_purchase1 %>%
  # filter(!(appliance %in% c("Clothes Dryer", "Dishwasher")))
# exclude the outliers
data_purchase1 <- data_purchase1 %>% 
                  filter(z_value > -0.5,
                         z_value < 0.5)
```

```{r}
# z_value outliers
outlier_z_value <- data.frame()
# filter to a needed dependent variable
outlier_z_value <- appliances %>%
  filter(dep_variable_purchase_category %in% c("purschase (probability) of efficient appliance", "WTP for efficient appliance"))
# exclude the outliers
outlier_z_value <- outlier_z_value %>% 
                  filter(z_value < -0.5 |
                         z_value > 0.5)
# Anderson, Claxton (1982) - fridge - economic - revealed
# Schultz et al. (2015) - very specific intensive intervention - a marketing campaign - lighting - economic - revealed
# Train, Atherton (1995) x5 - confusing modelling - fridge, ac - information - stated
# Li et al. (2021) - fridge - economic - stated
# Skourtos et al. (2021) x4 - fridge - economic - stated
# Ward et al. (2021) x2 - fridge - economic - stated
```

```{r}
# carry out the same analysis without any exclusions
# include WTP and purchase probability together
data_purchase3 <- data.frame()
# filter to a needed dependent variable
data_purchase3 <- appliances %>%
  filter(dep_variable_purchase_category %in% c("purschase (probability) of efficient appliance", "WTP for efficient appliance"))

count <- table(data_purchase3$intervention)
print(count)
```

```{r}
# WTP separately
data_wtp <- data.frame()
# filter to a needed dependent variable
data_wtp <- appliances %>%
  filter(dep_variable_purchase_category == "WTP for efficient appliance")
# exclude the outliers
data_wtp <- data_wtp %>% 
                  filter(z_value > -0.5,
                         z_value < 0.5)
```

```{r}
### MULTI-LEVEL MODEL ###
# on purchase probability only
# redundant predictors dropped from the model

# Step 1: Create a meta-analysis model
meta_model1 <- rma(z_value, z_variance, data = data_purchase, method = "FE", mods = ~ intervention+0)
meta_model2 <- rma(z_value, z_variance, data = data_purchase, method = "FE", mods = ~ appliance+0)
# dishwasher and heat pump are showing insignificant negative results
meta_model3 <- rma(z_value, z_variance, data = data_purchase, method = "REML", mods = ~ intervention+0)
meta_model4 <- rma(z_value, z_variance, data = data_purchase, method = "REML", mods = ~ appliance+0)
# clothes dryer and dishwasher show insignificant negative results

# Step 2: Fit the meta-analysis model
meta_model5 <-rma.mv(z_value, z_variance, mods =  ~ intervention+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase, method = "REML")
meta_model6 <-rma.mv(z_value, z_variance, mods = ~ appliance+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase, method = "REML")
# make graphs from this
summary(meta_model1)
# fixed effects by intervention
# feedback, label, rebate and subsidy significant positive
summary(meta_model2)
# fixed effects by appliance
# AC, light, fridge, tv, washing machine significant positive
summary(meta_model3)
# random effects by intervention
# all apart from loan significant positive
summary(meta_model4)
# random effects by appliance
# AC, light, washing machine, water heater significant positive
summary(meta_model5)
# random effects multi-level by intervention
# all apart from loan significant positive
summary(meta_model6)
# random effects multi-level by appliance
# AC, light, fridge, tv, washing machine, water heater significant positive

# most of the interventions / appliances that do not show significant effects are very small in sample size
```

```{r}
### PURCHASE PROBABILITY + WTP (excl. outliers)
### FIXED EFFECTS ###
meta_model1 <- rma(z_value, z_variance, data = data_purchase1, method = "FE", mods = ~ intervention+0)
# fixed effects by intervention
# feedback, label, rebate, subsidy significant positive
meta_model2 <- rma(z_value, z_variance, data = data_purchase1, method = "FE", mods = ~ appliance+0)
# fixed effects by appliance
# AC, light, fridge, tv, washing machine, water heater significant positive

### RANDOM EFFECTS ###
meta_model3 <- rma(z_value, z_variance, data = data_purchase1, method = "REML", mods = ~ intervention+0)
# random effects by intervention
# feedback, information, label, rebate, subsidy significant positive
meta_model4 <- rma(z_value, z_variance, data = data_purchase1, method = "REML", mods = ~ appliance+0)
# random effects by appliance
# AC, light, fridge, washing machine, water heater significant positive

### MULTI-LEVEL MODEL ###
meta_model5 <-rma.mv(z_value, z_variance, mods =  ~ intervention + 0, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase1, method = "REML")
# random effects multi-level by intervention
# feedback, information, label, rebate, subsidy significant positive
meta_model6 <-rma.mv(z_value, z_variance, mods = ~ appliance + 0,  
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase1, method = "REML")
# random effects multi-level by appliance
# AC, light, fridge, tv, washing machine, water heater significant positive

### INTERACTION INTERVENTION X APPLIANCE ###
data_purchase2 <- data_purchase1 %>%
  filter(appliance %in% c("Refrigerator", "Air-Conditioner", "Water Heater"))

meta_model7 <-rma.mv(z_value, z_variance, mods =  ~ intervention_category:appliance+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase2, method = "REML")
# economic incentives x refrigerator have a negative sign  
summary(meta_model5)
```

```{r}
### PURCHASE PROBABILITY + WTP (incl. outliers)
### FIXED EFFECTS ###
meta_model1 <- rma(z_value, z_variance, data = data_purchase3, method = "FE", mods = ~ intervention+0)
# fixed effects by intervention
# all significant positive
meta_model2 <- rma(z_value, z_variance, data = data_purchase3, method = "FE", mods = ~ appliance+0)
# fixed effects by appliance
# AC, light, fridge, tv, washing machine, water heater significant positive

### RANDOM EFFECTS ###
meta_model3 <- rma(z_value, z_variance, data = data_purchase3, method = "REML", mods = ~ intervention+0)
# random effects by intervention
# information, label, rebate significant positive
meta_model4 <- rma(z_value, z_variance, data = data_purchase3, method = "REML", mods = ~ appliance+0)
# random effects by appliance
# AC, light, fridge, washing machine, water heater significant positive

### MULTI-LEVEL MODEL ###
meta_model0 <-rma.mv(z_value, z_variance, mods =  ~ dep_variable_purchase_category, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")

meta_model0 <-rma.mv(z_value, z_variance, mods =  ~ intervention_category, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")

# take out outliers here and compare results

#Above results show that there is no statistical difference between effect sizes for 1) wtp and purchase prob 2)monetary incentives and info strategies

meta_model5 <-rma.mv(z_value, z_variance, mods =  ~ intervention+0, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_model5)

meta_model5_1 <-rma.mv(z_value, z_variance, mods =  ~ intervention, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_model5_1)
# random effects multi-level by intervention
# information, label, rebate significant positive
meta_model6 <-rma.mv(z_value, z_variance, mods = ~ appliance + 0,  
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_model6)
# random effects multi-level by appliance
# light, fridge, tv, washing machine significant positive


### INTERACTION INTERVENTION X APPLIANCE ###
data_purchase4 <- data_purchase3 %>%
  filter(appliance %in% c("Refrigerator", "Lighting", "Washing Machine"))

meta_model7 <-rma.mv(z_value, z_variance, mods =  ~ intervention_category:appliance+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase4, method = "REML")
# economic incentives x refrigerator have a negative sign  
summary(meta_model7)

# run a model with control variables included
control_formula <- as.formula(paste("~", paste(controlvars, collapse = "+"), "+ 0"))
meta_model8 <-rma.mv(z_value, z_variance, mods = control_formula,  
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
# contrasts can be applied only to factors with 2 or more levels
# Iterate over variables in the dataset
for (var in controlvars) {
  # Check the number of levels in each variable
  num_levels <- nlevels(data_purchase3[[var]])
  
  # Print the variable name if it has only one level
  if (num_levels < 2) {
    print(paste("Variable", var, "has only one level"))
  }
}
# numeric and binary variables are causing errors

# effects don't change too much from inclusion of 'outliers'
# AC results change quite a bit, although there was only one effect size on AC 
# Train papers show weird results for loan and z_values 
# Skourtos paper has both high variance and z_value

summary(meta_model8)
```

```{r}
avgffect_bygroup<- filter(data_purchase3) %>%
  group_by(appliance, intervention) %>% 
  summarise(avg = mean(z_value, na.rm = TRUE))%>%
  pivot_wider(names_from = intervention, values_from = avg)%>%
  print()
```

```{r}
### FREQUENCY TABLES AND DISTRIBUTIONS
ggplot(data_purchase3, aes(x = z_value, y = z_variance , colour = appliance)) +
  # scale_y_continuous(limits = c(-0.05,.5))+
  geom_point(size = 2, alpha = 0.25) +
  #geom_jitter(width = .1, alpha = .25) +
  labs(x = "z_value", y = "variance") +
  facet_wrap(vars(data_purchase3$intervention))+ 
  theme_bw()
```

```{r}
# outlier check 
outlier_variance <- data_purchase1 %>% 
  filter(z_variance > 0.02)

loan <- data_purchase1 %>%
  filter(intervention == "Loan")
# all insingificant apart from revealed preference in Train & Atherton and Liu, Jin
# all significant effects are negative
# consistent with the findings described in the primary studies
```


```{r}
ggplot(data_purchase3, aes(x = year_data_study, y = z_value, colour = appliance)) +
  # scale_y_continuous(limits = c(-0.05,.5))+
  geom_point(size = 2, alpha = 0.25) +
  #geom_jitter(width = .5, alpha = .25) +
  labs(x = "", y = "z_value") +
  theme_bw()
```

```{r}
# Effect level analysis 

ggplot(data_purchase3, aes(x = z_value, y = intervention, colour = intervention)) +
  geom_density_ridges2(fill = "lightblue", alpha = 0.5, scale = .8, 
                       quantile_lines = TRUE, quantiles = c(0.5)) + 
  geom_jitter(height = .1, alpha = .1)

ggplot(data_purchase3, 
              aes(x = z_value, y = appliance, colour = appliance)) +
  geom_density_ridges2(fill = "lightblue", alpha = 0.5, scale = 1, 
                       quantile_lines = TRUE, quantiles = c(0.5)) + 
  geom_jitter(height = .1, alpha = .1)

# Summary by group using dplyr

data_purchase3 %>%                               
  group_by(appliance) %>% 
  summarize(min = min(z_value, na.rm = T),
            q1 = quantile(z_value, 0.25, na.rm = T),
            median = median(z_value, na.rm = T),
            mean = mean(z_value, na.rm = T),
            q3 = quantile(z_value, 0.75, na.rm = T),
            max = max(z_value, na.rm = T))


ggplot(data_purchase3, aes(x = z_value, y = as.factor(outOfSampleBias))) +
  geom_density_ridges2(fill = "lightblue", alpha = 0.5, scale = .8, 
                       quantile_lines = TRUE, quantiles = c(0.5)) +
  geom_jitter(height = .1, alpha = .1) 

ggplot(data_purchase3, aes(x = z_value, y = as.factor(reportingBiases))) +
  geom_density_ridges2(fill = "lightblue", alpha = 0.5, scale = .8, 
                       quantile_lines = TRUE, quantiles = c(0.5)) +
  geom_jitter(height = .1, alpha = .1) 
```

```{r}
### PUBLICATION BIAS ASSESSMENT ###
library(lmtest)

### EGGERS TEST ###

funnel(data_purchase3$z_value, 
       v = data_purchase3$z_variance,
       # level = c(90, 95, 99),
       # shade = c("white", "gray55", "gray75"),
       ylim = c(0, .3),
       col = as.factor(data_purchase3$intervention), 
       legend =F)

# Define a color palette with enough colors for each unique appliance
my_colors <- c("blue", "red", "green", "purple", "orange", "yellow", "pink", "brown", "gray")

# Create the plot
funnel(data_purchase3$z_value, 
       v = data_purchase3$z_variance,
       ylim = c(0, .3),
       col = my_colors[as.factor(data_purchase3$appliance)], 
       legend = FALSE)

# Get unique appliance values
unique_appliances <- unique(data_purchase3$appliance)

# Add the legend
legend("topright", legend = unique_appliances, col = my_colors[1:length(unique_appliances)], pch = 1)

data_purchase3$se = (data_purchase3$z_variance)^(1/2)

meta_egger1 <-rma.mv(z_value, z_variance, mods =  ~ intervention+se, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_egger1)

meta_egger2 <-rma.mv(z_value, z_variance, mods =  ~ appliance+se, # add all moderator variables
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_egger2)

# 
# # what does this do? 
# robust(rma.mv(z_value, v, random = ~ as.factor(sr_no) | as.factor(study_ID), 
#                      mods = ~ v, data = dfinc5, method = "REML"), cluster = as.factor(study_ID), clubSandwich = T)
# robust(rma(z_value, v, 
#                      mods = ~ v, data = dfinc5, method = "FE"), cluster = study_ID, clubSandwich = T)

# bias correction
```

```{r}
# identify outliers
# outliers in loan and rebate (strong negative effects)
# outliers by variance (> 0.25)
# outliers by z_value > 0.5 or < - 0.5
threshold <- 0.2

x5 <- cooks.distance(meta_model5)
plot(x5, type="o", pch=19, xlab="Observed Outcome", ylab="Cook's Distance")
text(x5,labels=names(x5))

above_threshold_rows5 <- which(x5 > threshold)
outlier_cooksd5 <- data_purchase3[above_threshold_rows5,]

above_threshold_rows5 <- which(x5 > threshold)
outlier_cooksd5 <- data_purchase3[above_threshold_rows5,]

x6 <- cooks.distance(meta_model6)
plot(x6, type="o", pch=19, xlab="Observed Outcome", ylab="Cook's Distance")
text(x6,labels=names(x6))

above_threshold_rows6 <- which(x6 > threshold)
outlier_cooksd6 <- data_purchase3[above_threshold_rows6,]

# y <- dfbetas(meta_model5, progbar=FALSE, reestimate=F, parallel="multicore")
# plot(y$intrcpt, type="o", pch=19, xlab="Observed Outcome", ylab="DFBetas")

```

```{r}

### 20.06.23 TESTING OUTLIERS ###

data_purchase5 <- data_purchase3 %>%
  filter(! sr_no %in% outlier_cooksd5$sr_no) %>%
  filter(! intervention == "Loan")

meta_model5_1 <-rma.mv(z_value, z_variance, mods =  ~ intervention+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase5, method = "REML")

data_purchase6 <- data_purchase3 %>%
  filter(! sr_no %in% outlier_cooksd6$sr_no) %>%
    filter(! intervention == "Loan")

meta_model6_1 <-rma.mv(z_value, z_variance, mods = ~ appliance + 0,  
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase6, method = "REML")
summary(meta_model5_1)
summary(meta_model6_1)

meta_model0_1 <-rma.mv(z_value, z_variance, mods =  ~ intervention_category + 0,
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase5, method = "REML")
summary(meta_model0_1)

data_purchase7 <- data_purchase3 %>%
  #filter(! sr_no %in% outlier_cooksd5$sr_no) %>%
  #filter(! sr_no %in% outlier_cooksd6$sr_no) %>%
  filter(! intervention == "Loan") %>%
  filter(appliance %in% c("Air-Conditioner", "Lighting","Refrigerator","Washing Machine"))

meta_model7 <-rma.mv(z_value, z_variance, mods =  ~ intervention_category:appliance+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase7, method = "REML")
summary(meta_model7)

data_purchase3 <- data_purchase3 %>%
  filter(! study_ID == 123) %>%
  filter(! intervention == "Loan")

data_purchase3_1 <- data_purchase3 %>%
  filter(! sr_no %in% outlier_cooksd5)

meta_model5_1 <-rma.mv(z_value, z_variance, mods =  ~ intervention+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
meta_model6_1 <-rma.mv(z_value, z_variance, mods =  ~ appliance+0, 
                               random = ~ as.factor(sr_no) | as.factor(study_ID), data = data_purchase3, method = "REML")
summary(meta_model6_1)
```


```{r}
# create a list of control variables
controlvars <- c( "intervention", "appliance")
                 # "continent",
                 # "statistical_technique",
                 #   "study_design",
                 #   "incentive_follow_through",
                 #   "experimental_setting",
                 #   "participant_type",
                 # "aware_of_study",
                 # "opt_in",
                 # "randomisation_dummy",
                 # "outOfSampleBias",
                 # "reportingBiases")
                 # "controls_energy_prices",
                 # "controls_environmental_attitudes",
                 # "controls_demographics")

metregvar <- c("z_value")
dfbms <- data_purchase3 %>%  select(all_of(metregvar))
dfbms <- mutate_if(dfbms, is.character, as.numeric)
dfbms <- mutate_if(dfbms, is.logical, as.numeric)
```

```{r}

# create binary variables for all control factor variables

# iterate over each factor variable
for (var_name in controlvars) {
  
  # get unique factor levels
  
  levels <- unique(data_purchase3[[var_name]])
  
  # create binary variables for each factor level
  for (level in levels[-1]) {
    # create a new column name by appending the factor level to the variable name
    new_col_name <- paste(var_name, level, sep = "_")
    
    # create a binary variable for the current factor level
    dfbms[[new_col_name]] <- as.numeric(data_purchase3[[var_name]] == level)
  }
}
summary(dfbms)

# dfbms <- dfbms %>% select(-c(intervention_Information, appliance_Lighting))
```

```{r}
library(BMS)
percent = bms(dfbms, burn=1e5,iter=3e5, g="UIP", mprior="uniform", nmodel=50000, mcmc="bd", user.int=FALSE)
# percent1 = bms(dfbms, burn=1e5,iter=3e5, g="UIP", mprior="dilut", nmodel=50000, mcmc="bd", user.int=FALSE)
# percent2 = bms(dfbms, burn=1e5,iter=3e5, g="BRIC", mprior="random", nmodel=50000, mcmc="bd", user.int=FALSE)
# percent3 = bms(dfbms, burn=1e5,iter=3e5, g="hyper=BRIC", mprior="random", nmodel=50000, mcmc="bd", user.int=FALSE)

coef <- as.data.frame(coef(percent, order.by.pip = T, exact=T, include.constant=T))
print(coef)
# image(percent, yprop2pip=FALSE, order.by.pip=T, do.par=TRUE, do.grid=TRUE, do.axis=TRUE, cex.axis = 0.7)



```


```{r}
# filter by appliance to test basic models
data_purchase_washing <- data_purchase %>% 
                  filter(washing_machine == 1)

data_purchase_dryer <- data_purchase %>% 
                  filter(clothes_dryer == 1)

data_purchase_dishwasher <- data_purchase %>% 
                  filter(dishwasher == 1)

data_purchase_refrigerator <- data_purchase %>% 
                  filter(refrigerator == 1)

data_purchase_heat_pump <- data_purchase %>% 
                  filter(heat_pump == 1)

data_purchase_lighting <- data_purchase %>% 
                  filter(lighting == 1)

data_purchase_water <- data_purchase %>% 
                  filter(water_heater == 1)

data_purchase_ac <- data_purchase %>% 
                  filter(ac == 1)

data_purchase_tv <- data_purchase %>% 
                  filter(tv == 1)
```

```{r}
### RANDOM EFFECTS MODEL ###
##washing machine
m.gen_purchase_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_washing,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_washing_random.png", width = 6000, height = 3000, res = 500)
forest.meta(m.gen_purchase_washing,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS MODEL ###
  
m1.gen_purchase_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_washing,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_washing_fixed.png", width = 6000, height = 3000, res = 500)
forest.meta(m1.gen_purchase_washing,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")       
```


```{r}
##dishwasher
### RANDOM EFFECTS ###
m.gen_purchase_dishwasher <- metagen(data = data_purchase_dishwasher,
                                  TE = z_value,
                                  seTE = z_variance,
                                  studlab = authors,
                                  sm = "ZCOR",
                                  fixed = FALSE,
                                  random = TRUE,
                                  backtransf = F)

## forest plot of purchase
png(file = "forestplot_dishwasher_random.png", width = 5000, height = 2000, res = 500)
forest.meta(m.gen_purchase_dishwasher,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_dishwasher <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_dishwasher,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of purchase
png(file = "forestplot_dishwasher_fixed.png", width = 5000, height = 2000, res = 500)
forest.meta(m1.gen_purchase_dishwasher,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

 
```


```{r}
##refrigerator
### RANDOM EFFECTS ###
m.gen_purchase_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_refrigerator,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_refrigerator_random.png", width = 7000, height = 3500, res = 500)
forest.meta(m.gen_purchase_refrigerator,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_refrigerator,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of purchase
png(file = "forestplot_refrigerator_fixed.png", width = 7000, height = 3500, res = 500)
forest.meta(m1.gen_purchase_refrigerator,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 
           
```

```{r}
##heatpump
### RANDOM EFFECTS ### 
m.gen_purchase_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_heat_pump,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase
png(file = "forestplot_heatpump_random.png", width = 5000, height = 1800, res = 500)
forest.meta(m.gen_purchase_heat_pump,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ### 

m1.gen_purchase_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_heat_pump,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of purchase
png(file = "forestplot_heat_pump_fixed.png", width = 5000, height = 2000, res = 500)
forest.meta(m1.gen_purchase_heat_pump,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 

 
```


```{r}
##lighting
### RANDOM EFFECTS ###
m.gen_purchase_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_lighting,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_lighting_random.png", width = 7000, height = 3500, res = 500)
forest.meta(m.gen_purchase_lighting,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###

m1.gen_purchase_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_lighting,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_lighting_fixed.png", width = 7000, height = 3500, res = 500)
forest.meta(m1.gen_purchase_lighting,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 

```


```{r}
##waterheater
### RANDOM EFFECTS ###
m.gen_purchase_water <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_water,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_water_random.png", width = 5500, height = 4500, res = 500)
forest.meta(m.gen_purchase_water,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_water <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_water,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_water_fixed.png", width = 5500, height = 4500, res = 500)
forest.meta(m1.gen_purchase_water,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```

```{r}
## tv
### RANDOM EFFECTS ###
m.gen_purchase_tv <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_tv,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_tv_random.png", width = 5500, height = 2600, res = 500)
forest.meta(m.gen_purchase_tv,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_tv <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_tv,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_tv_fixed.png", width = 5500, height = 2600, res = 500)
forest.meta(m1.gen_purchase_tv,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```


```{r}
##airconditioning
### RANDOM EFFECTS ###
m.gen_purchase_ac <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_ac,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_air_random.png", width = 5500, height = 3000, res = 500)
forest.meta(m.gen_purchase_ac,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_ac <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_ac,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_air_fixed.png", width = 5500, height = 3000, res = 500)
forest.meta(m1.gen_purchase_ac,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```

```{r}
## dryer
### RANDOM EFFECTS ###
m.gen_purchase_dryer <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_dryer,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_dryer_random.png", width = 5500, height = 2600, res = 500)
forest.meta(m.gen_purchase_dryer,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_purchase_dryer <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_dryer,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of purchase

png(file = "forestplot_dryer_fixed.png", width = 5500, height = 2600, res = 500)
forest.meta(m1.gen_purchase_dryer,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```




