---
title: "wtp"
author: "D. Danilenko"
date: "2023-05-11"
output: html_document
---

```{r setup, include=FALSE}
setwd("/Users/dianadanilenko/Desktop/appliances_analysis/wtp")
```


```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(meta)
library(metafor)
library(metadat)
library(haven)
library(writexl)
library(openxlsx)
library(dplyr)
library(stringr)
library(readxl)
options(scipen = 999)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
applianceswtp <- read_xlsx("appliances_wtp.xlsx", sheet = "Appliances")
applianceswtp$z_value <- as.numeric(applianceswtp$z_value)
applianceswtp$z_value <- ifelse(applianceswtp$effect_direction == "decrease",
                                   -applianceswtp$z_value,
                                   applianceswtp$z_value)
applianceswtp$z_variance <- as.numeric(applianceswtp$z_variance)
```

```{r}
summary(applianceswtp)
```

```{r}
## Subset dataset for each appliance and intervention in wtp
## We want to regroup by interventions and then only arrange by appliance
## rebate, tax_credit, subsidy, loan can be grouped into monetary ? 
data_wtp <- applianceswtp %>% 
              mutate(Intervention = case_when(feedback == 1 ~ "Feedback",
                                              information == 1 ~ "Information",
                                              label == 1 ~ "Label",
                                              rebate == 1 ~ "Rebate",
                                              tax_credit == 1 ~ "Tax",
                                              subsidy == 1 ~ "Subsidy",
                                              loan == 1 ~ "Loan",
                                              choice_architecture == 1 ~ "Choice Architecture"))

data_wtp_washing <- data_wtp %>% 
                  filter(washing_machine == 1)

data_wtp_dryer <- data_wtp %>% 
                  filter(clothes_dryer == 1)

data_wtp_dishwasher <- data_wtp %>% 
                  filter(diswasher == 1)

data_wtp_refrigerator <- data_wtp %>% 
                  filter(refrigerator == 1)

data_wtp_heat_pump <- data_wtp %>% 
                  filter(heat_pump == 1)

data_wtp_lighting <- data_wtp %>% 
                  filter(lighting == 1)

data_wtp_water <- data_wtp %>% 
                  filter(water_heater == 1)

data_wtp_ac <- data_wtp %>% 
                  filter(ac == 1)

data_wtp_tv <- data_wtp %>% 
                  filter(tv == 1)
```

```{r}
### RANDOM EFFECTS MODEL ###
##washing machine
m.gen_wtp_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_washing,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_washing_random.png", width = 5000, height = 1500, res = 500)
forest.meta(m.gen_wtp_washing,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS MODEL ###
  
m1.gen_wtp_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_washing,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_washing_fixed.png", width = 5000, height = 1500, res = 500)
forest.meta(m1.gen_wtp_washing,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")       
```


```{r}
##dishwasher
### RANDOM EFFECTS ###
m.gen_wtp_dishwasher <- metagen(data = data_wtp_dishwasher,
                                  TE = z_value,
                                  seTE = z_variance,
                                  studlab = authors,
                                  sm = "ZCOR",
                                  fixed = FALSE,
                                  random = TRUE,
                                  backtransf = F)

## forest plot of wtp
png(file = "forestplot_dishwasher_random.png", width = 5000, height = 2000, res = 500)
forest.meta(m.gen_wtp_dishwasher,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_dishwasher <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_dishwasher,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of wtp
png(file = "forestplot_dishwasher_fixed.png", width = 5000, height = 2000, res = 500)
forest.meta(m1.gen_wtp_dishwasher,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

 
```


```{r}
##refrigerator
### RANDOM EFFECTS ###
m.gen_wtp_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_refrigerator,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_refrigerator_random.png", width = 7000, height = 4000, res = 500)
forest.meta(m.gen_wtp_refrigerator,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_refrigerator,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of wtp
png(file = "forestplot_refrigerator_fixed.png", width = 7000, height = 4000, res = 500)
forest.meta(m1.gen_wtp_refrigerator,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 
           
```

```{r}
##heatpump
### RANDOM EFFECTS ### 
m.gen_wtp_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_heat_pump,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp
png(file = "forestplot_heatpump_random.png", width = 5000, height = 1800, res = 500)
forest.meta(m.gen_wtp_heat_pump,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ### 

m1.gen_wtp_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_heat_pump,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F)
## forest plot of wtp
png(file = "forestplot_heat_pump_fixed.png", width = 5000, height = 2000, res = 500)
forest.meta(m1.gen_wtp_heat_pump,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 

 
```


```{r}
##lighting
### RANDOM EFFECTS ###
m.gen_wtp_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_lighting,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_lighting_random.png", width = 7000, height = 3500, res = 500)
forest.meta(m.gen_wtp_lighting,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###

m1.gen_wtp_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_lighting,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_lighting_fixed.png", width = 7000, height = 3500, res = 500)
forest.meta(m1.gen_wtp_lighting,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
 

```


```{r}
##waterheater
### RANDOM EFFECTS ###
m.gen_wtp_water <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_water,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_water_random.png", width = 5500, height = 4500, res = 500)
forest.meta(m.gen_wtp_water,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_water <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_water,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_water_fixed.png", width = 5500, height = 4500, res = 500)
forest.meta(m1.gen_wtp_water,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```

```{r}
## tv
### RANDOM EFFECTS ###
m.gen_wtp_tv <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_tv,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_tv_random.png", width = 5500, height = 2600, res = 500)
forest.meta(m.gen_wtp_tv,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_tv <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_tv,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_tv_fixed.png", width = 5500, height = 2600, res = 500)
forest.meta(m1.gen_wtp_tv,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```


```{r}
##airconditioning
### RANDOM EFFECTS ###
m.gen_wtp_ac <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_ac,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_air_random.png", width = 5500, height = 3000, res = 500)
forest.meta(m.gen_wtp_ac,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_ac <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_ac,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_air_fixed.png", width = 5500, height = 3000, res = 500)
forest.meta(m1.gen_wtp_ac,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```

```{r}
## dryer
### RANDOM EFFECTS ###
m.gen_wtp_dryer <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_dryer,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_dryer_random.png", width = 5500, height = 2600, res = 500)
forest.meta(m.gen_wtp_dryer,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

### FIXED EFFECTS ###
m1.gen_wtp_dryer <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_wtp_dryer,
                 studlab = authors,
                 sm = "ZCOR",
                 fixed = TRUE,
                 random = FALSE,
                 backtransf = F,
                 )

## forest plot of wtp

png(file = "forestplot_dryer_fixed.png", width = 5500, height = 2600, res = 500)
forest.meta(m1.gen_wtp_dryer,
           leftcols = c("authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
```






