---
title: "marketshare"
author: "D. Danilenko"
date: "2023-05-11"
output: html_document
---

```{r setup, include=FALSE}
setwd("C:/Users/dand/OneDrive/Desktop/GitHub/appliances_interventions")
```

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(meta)
library(metafor)
library(metadat)
library(haven)
library(writexl)
library(openxlsx)
library(dplyr)
library(stringr)
library(readxl)
options(scipen = 999)
load("appliances_clean.R")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r subset data}
data_marketshare <- data.frame()
# filter to a needed dependent variable
data_marketshare <- appliances %>% 
                  filter(dep_variable_purchase_category == "market share of efficient appliance")
```

```{r process data}
data_marketshare$percent_change <- ifelse(is.na(data_marketshare$percent_change),
                                    data_marketshare$coefficient,
                                    data_marketshare$percent_change)

data_marketshare$percent_change <- data_marketshare$percent_change*100

data_marketshare$percent_change_ci <-  ifelse(data_marketshare$study_ID == "114",
                                       data_marketshare$percent_change/abs(data_marketshare$t_stat),
                                       data_marketshare$coefficient_se*100)
# exclude outliers for visualisation purpose
data_marketshare <- data_marketshare %>% 
                  filter(percent_change > -30)
                   
data_marketshare <- data_marketshare %>% 
                  filter(percent_change < 30)

unique_studies_marketshare <- unique(data_marketshare$study_ID)
```

```{r frequency table}
library(ggrepel)
library(RColorBrewer)
palette <- brewer.pal(num_appliances, "Set1")

intervention_colors <- setNames(palette, unique(data_marketshare$intervention))
appliance_colors <- setNames(palette, unique(data_marketshare$appliance))

### FREQUENCY TABLE
ggplot(data_marketshare, aes(x = percent_change, y = percent_change_ci , colour = appliance)) +
  # scale_y_continuous(limits = c(-0.05,.5))+
  geom_point(size = 2, alpha = 0.75) +
  #geom_jitter(width = .1, alpha = .25) +
  labs(x = "percent_change", y = "variance") +
  scale_colour_manual(values = appliance_colors) +
  facet_wrap(vars(data_marketshare$intervention))+ 
  theme_bw()
```

```{r folded forest plot}
data_marketshare$sr_no <- as.factor(data_marketshare$sr_no)
library(stringr)

data_marketshare$author <- str_extract(data_marketshare$authors, "^[^,]+")  # Extract the first author's name
data_marketshare$author <- paste(data_marketshare$author, "et al.")  # Append "et al."
data_marketshare['author_year'] <- paste0(data_marketshare$author, " (",data_marketshare$year_publication,")")
data_marketshare['author_year_srno'] <- paste0(data_marketshare$author, " (",data_marketshare$year_publication,")", " ", data_marketshare$sr_no)

fp <- ggplot(data = data_marketshare, aes(x = author_year_srno, y = percent_change, 
                                          ymin = percent_change - percent_change_ci, 
                                          ymax = percent_change + percent_change_ci, 
                                          colour = intervention)) +
        geom_pointrange(size = 0.5) + 
        geom_hline(yintercept = 0, lty = 2) +  # Add a dotted line at y = 0
        coord_flip() +  # Flip coordinates (puts labels on y axis)
        ylab("Mean Percentage Change") + xlab("") +
        scale_colour_manual(values = intervention_colors) +
        theme_bw() +
        geom_label(aes(label = paste0(round(percent_change, 2), "%")), 
                   size = 2.25, colour = "black", 
                   vjust = 1.5, hjust = 0.75)+  # Move the label above the point (adjust as needed)
                   #nudge_y = -1.5) +  # Manually adjust the label position upward
        facet_wrap(~ appliance, scales = "free_y") +  # Facet by appliance to keep labels separate
        scale_x_discrete(
            breaks = data_marketshare$author_year_srno,  # Use the full value for positioning
            labels = data_marketshare$author_year  # Display only the author_year on the axis
        )

print(fp)
ggsave("marketshare_appliance.png", plot = fp, width = 10, height = 8)
```






